cc_library(
    name = "opennurbs",
    srcs = glob(
        ["*.cpp"],
        exclude = [
            "opennurbs_unicode_cp932.cpp",
            "opennurbs_unicode_cp949.cpp",
        ],
    ),
    hdrs = glob(
        ["*.h"],
        exclude = ["opennurbs_internal_unicode_cp.h"],
    ),
    defines = ["ON_COMPILING_OPENNURBS"],
    deps = [
        "@libuuid",
        "@zlib",
    ],
)
